# Generated by Django 2.0.8 on 2018-09-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_Logo',
            new_name='album_Logo',
        ),
    ]
